name: Deploy release

on:
  pull_request:
    branches:
      - 'release'
    types: [closed]

jobs:
  deployRelease:
    if: ${{ github.event.pull_request.merged }}
    name: Deploy release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install deps
        run: npm ci

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  downloadArtifact:
    name: Download artifact
    needs: [deployRelease]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build

  deployResults:
    name: Deploy results
    needs: [downloadArtifact]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy results
        uses: ./.github/actions/deploy-results
        with:
          myToken: ${{ secrets.MY_TOKEN }}
          pullRequestTitle: ${{ github.event.pull_request.title }}
          pullRequestNumber: ${{ github.event.pull_request.number }}
