name: Deploy release

on:
  pull_request:
    branches:
      - 'release'
    types: [closed]

jobs:
  deployRelease:
    if: ${{ github.event.pull_request.merged }}
    name: Deploy release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install deps
        run: npm ci

      - name: Deploy
        run: npm run deploy

  deployResults:
    name: Deploy results
    needs: [deployRelease]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test results
        uses: ./.github/actions/deploy-results
        with:
          myToken: ${{ secrets.MY_TOKEN }}
          jobName: 'Deploy release'
          pullRequestTitle: ${{ github.event.pull_request.title }}
