name: Init release

on: [workflow_dispatch]

jobs:
  InitRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init release
        uses: ./.github/actions/init-release
        with:
          myToken: ${{ secrets.MY_TOKEN }}
