name: Init release

on:
  workflow_dispatch:
    inputs:
      Name:
        description: Release name
        required: true

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init release
        uses: ./.github/actions/hello
        with:
          Name: ${{ github.event.inputs.Name }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
